# Generated by Django 5.0.6 on 2024-08-08 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('centre_name', models.CharField(max_length=255)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('working_hours_start', models.TimeField()),
                ('working_hours_end', models.TimeField()),
                ('available_slots', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('centre_name', models.CharField(max_length=255)),
                ('slot', models.CharField(max_length=255)),
                ('num_slot', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
