# Generated by Django 5.0.6 on 2024-08-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinationcenter',
            old_name='centre_name',
            new_name='center_name',
        ),
    ]
